name: Debugging Agent Testing
on: 
   push:
    branches: ["main"]
   pull_request: 
    branches: ["main"]
jobs:
    test-suite: 
        runs-on: windows-latest

        steps: 
        - name: Checkout Code
          uses: actions/checkout@v5
        
        - name: Setup Python 3.11.4 
          uses: actions/setup-python@v5
          with: 
            python-version: '3.11.4'
            cache: 'pip'
        
        - name: Display Python Version
          run: |
            echo "::group::System Information"
            python --version
            echo "OS Details"
            systeminfo | findstr /B /C:"OS NAME" /C:"OS Version"
            echo "::endgroup::"
        
        - name: Install Dependencies
          run: | 
            python -m pip install --upgrade pip 
            pip install -r requirements.txt
            echo "::group::Python Package List"
            pip list
            echo "::endgroup::"

            Write-Host "All checks done."



